# Generated by Django 3.1.3 on 2023-11-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGpt',
            new_name='Chat',
        ),
    ]
