# Generated by Django 3.1.3 on 2023-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('firtname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('confirmpassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='quetion',
            field=models.CharField(max_length=500),
        ),
    ]
