# Generated by Django 3.1.3 on 2023-11-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0007_remove_user_confirmpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
