# Generated by Django 3.1.3 on 2023-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('firtname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
