# Generated by Django 3.1.3 on 2023-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=500)),
            ],
        ),
    ]
