# Generated by Django 3.1.3 on 2023-12-03 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0010_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=1000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.user')),
            ],
        ),
        migrations.CreateModel(
            name='TalkToPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='talkpdf_documents')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('indexLoc', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='ResetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPTRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('userGenerated', models.BooleanField(default=False)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgpt.profiles')),
            ],
        ),
    ]
