# Generated by Django 3.1.3 on 2023-12-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0012_auto_20231204_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
