# Generated by Django 3.1.3 on 2023-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0013_auto_20231205_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('user', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=1000)),
            ],
        ),
    ]
