# Generated by Django 3.1.3 on 2023-12-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0014_questionanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
