# Generated by Django 3.1.3 on 2023-12-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0016_questionanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
