# Generated by Django 3.1.3 on 2024-01-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0020_questionanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
