# Generated by Django 3.1.3 on 2024-01-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0023_userrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
