# Generated by Django 3.1.3 on 2024-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0024_delete_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='quetion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
