# Generated by Django 3.1.3 on 2024-01-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0025_auto_20240112_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='question',
            new_name='quetion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='firtname',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
