# Generated by Django 3.1.3 on 2024-01-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0026_auto_20240113_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField()),
                ('year_level', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='stars',
        ),
    ]
